version: 2
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3
 
jobs:
    # build ジョブ: CircleCI 上で Docker コンテナを作成してテストする
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    
    # deploy ジョブ: EC2 に SSH 接続して、デプロイを実行する
    deploy:
        docker:
          - image: circleci/ruby:2.7
        steps:
            - checkout
            - setup_remote_docker:
                version: 19.03.13
            - run:
                name: heroku login
                command: wget https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli-linux-x64.tar.gz -O heroku.tar.gz
                command: sudo mkdir -p /usr/local/lib/heroku
                command: sudo tar --strip-components 1 -zxvf heroku.tar.gz -C /usr/local/lib/heroku
                command: sudo ln -s /usr/local/lib/heroku/bin/heroku /usr/local/bin/heroku
                command: heroku container:login
            - run:
                name: push docker image
                command: heroku container:push web -a $HEROKU_APP_NAME
            - run:
                name: release docker image
                command: heroku container:release web -a $HEROKU_APP_NAME
            - run:
                name: database setup
                command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME
     
workflows:
  version: 2
  build_rubocop_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master