version: 2
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3
 
jobs:
    # build ジョブ: CircleCI 上で Docker コンテナを作成してテストする
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    
    # deploy ジョブ: EC2 に SSH 接続して、デプロイを実行する
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            # CircleCI に登録した秘密鍵を呼び出す
            - add_ssh_keys:
            # CircleCI に登録した環境変数を使って SSH
            - run: eval "$(ssh-agent -s)"
            - run: ssh-add ~/.ssh/id_rsa
            - run: ssh ${USER_NAME}@${HOST_NAME} "cd kouch && git pull"
 
workflows:
  version: 2
  build_rubocop_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master